name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 构建
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPU

      - name: Install dependencies
        run: pnpm install

      # 构建
      - name: Run build
        run: pnpm build

      - name: ls
        run: ls -a

      # 上传到服务器
      - name: Upload files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: dist
          target: '/usr/share/nginx/html'

  # 发布
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Run Deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 4m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "[deploy] start deployment..."

            # 进到当前文件夹
            cd /usr/share/nginx/html

            echo "[deploy] ls..."
            ls -a

            # 删除缓存
            echo "[deploy] remove cache..."
            rm -rf admin

            # 添加刚刚打包的文件
            echo "[deploy] add .next..."
            mv dist admin

            echo "[deploy] ls..."
            ls -a

            echo "[deploy] end deployment..."
            echo "[deploy] success"
